version: '3'
services:
  postgres:
    container_name: postgres-bookstore
    image: postgres:14
    env_file:
      - backend/docker.env
    ports:
      - 5431:5432
    networks:
      - default
    volumes:
      - postgres:/data/postgres-bookstore
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-bookstore
    image: dpage/pgadmin4:6
    env_file:
      - backend/docker.env
    ports:
      - 9090:80
    networks:
      - default
    volumes:
      - pgadmin:/root/.pgadmin-bookstore
    restart: unless-stopped

  api:
    container_name: api-bookstore
    image: api-bookstore:1.0.0
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    command: npm run start:dev
    depends_on:
      - postgres
    ports:
      - 3000:3000
    networks:
      - default
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:

networks:
  default:
    driver: bridge
