### Requests done with REST-Client for VSCode (humao.rest-client) ###
@hostname = localhost
@port = 4000
@host = {{hostname}}:{{port}}
@contentType = application/json
@bookId = 1

###

// Get all books 
GET http://{{host}}/books

###

// Get specific book
# @bookId = 11
GET http://{{host}}/books/{{bookId}}

###

// Post a new book
POST http://{{host}}/books
Content-Type: {{contentType}}

{
    "isbn": 11,
    "title": "Itsi Me!",
    "description": "A book wrote by Mario?",
    "author": "Mario"
}
###
    "author": {
        "lastName": "Shroom",
        "firstName": "Mario"
    }
###

// Delete a specific book
# @bookId = 6
DELETE http://{{host}}/books?bookID={{bookId}}