version: '3'
services:
  postgres:
    container_name: postgres-bookstore
    image: postgres:latest
    ports:
      - '5431:5432'
    volumes:
      - /data/postgres-bookstore:/data/postgres-bookstore
    env_file:
      - docker.env
    networks:
      - bookstore

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin-bookstore
    image: dpage/pgadmin4
    ports:
      - '9090:80'
    volumes:
      - /data/pgadmin-bookstore:/root/.pgadmin-bookstore
    env_file:
      - docker.env
    networks:
      - bookstore

networks:
  bookstore:
    driver: bridge
